import type { UpgradeTrack } from '@mythos/core/character';
import UPGRADE_TRACKS from './upgradeTracks.json';

const TRACKS = UPGRADE_TRACKS as Record<string, UpgradeTrack>;

/**
 * The upgrade track an item's bonus ids encode ("Hero 6/6"), or null when
 * none of them is a track bonus. Blizzard's equipment API has no track
 * field of its own; upgradeTracks.json is generated by `bun run tracks:import`.
 */
export function upgradeTrackFor(bonusList: readonly number[] | undefined): UpgradeTrack | null {
  for (const id of bonusList ?? []) {
    const track = TRACKS[id];
    if (track) return track;
  }
  return null;
}
